theme: jekyll-theme-cayman
title: Microeconomía II  - 2021
description: En esta página encontrará material de apoyo para el curso Microeconomía II del Doctorado y Magíster en Economía de la Universidad de Chile. Profesor: Juan Pablo Torres-Martínez.

